const json =
    {
        "p1":
            {
                "name": "Puzzle Player",
                "life": 10,
                "mana": 10,
                "gems": "byrgop",
                "burn": false,
                "path":
                    {
                        "id": 3,
                        "name": "Fires of Creation",
                        "icon": "paths/forge.png",
                        "image": "fires_of_creation.png"
                    },
                "power":
                    {
                        "id": 5,
                        "name": "Reconstruct",
                        "icon": "powers/reconstruct.png",
                        "image": "reconstruct.png"
                    },
                "hand": [
                    {
                        "id": 2,
                        "id_rhino": 2,
                        "ide_faction": 1,
                        "rarity_index": 0,
                        "name": "Fey Plagiarist",
                        "name_export": "fey plagiarist",
                        "name_clean": "fey_plagiarist",
                        "image": "fey_plagiarist.png",
                        "set": "Core",
                        "type": "Creature",
                        "subtype": "Elf Hacker",
                        "rarity": "rare",
                        "max_in_deck": 2,
                        "cost": 1,
                        "gems": "b",
                        "attack": 1,
                        "health": 2,
                        "keywords": null,
                        "text": "Breach: Copy one of your opponent's artifacts or enchantments and add it to your hand without gems in its casting cost.\r\n",
                        "text_flavor": "\"If your IP is grokkable then it's open source.\" -Svartálfar artificer",
                        "created_at": null,
                        "updated_at": null
                    },
                    {
                        "id": 4,
                        "id_rhino": 4,
                        "ide_faction": 1,
                        "rarity_index": 2,
                        "name": "Freki Scout",
                        "name_export": "freki scout",
                        "name_clean": "freki_scout",
                        "image": "freki_scout.png",
                        "set": "Core",
                        "type": "Creature",
                        "subtype": "Valkyrie",
                        "rarity": "common",
                        "max_in_deck": 4,
                        "cost": 1,
                        "gems": "b",
                        "attack": 2,
                        "health": 1,
                        "keywords": "[\"Swift\"]",
                        "text": "Swift\r\n",
                        "text_flavor": "\"Only way forward is to get your wheels dirty, sister.\" -Ingrid Stormdottir",
                        "created_at": null,
                        "updated_at": null
                    },
                    {
                        "id": 6,
                        "id_rhino": 6,
                        "ide_faction": 1,
                        "rarity_index": 4,
                        "name": "Honed Edge",
                        "name_export": "honed edge",
                        "name_clean": "honed_edge",
                        "image": "honed_edge.png",
                        "set": "Core",
                        "type": "Spell",
                        "subtype": "Somatic Spell",
                        "rarity": "common",
                        "max_in_deck": 4,
                        "cost": 1,
                        "gems": "b",
                        "attack": 0,
                        "health": 0,
                        "keywords": null,
                        "text": "Give a minion +2/+1.\r\n",
                        "text_flavor": "I aim only to sharpen you, as I would any other weapon.",
                        "created_at": null,
                        "updated_at": null
                    }
                ],
                "deck": [
                    {
                        "id": 8,
                        "id_rhino": 8,
                        "ide_faction": 1,
                        "rarity_index": 1,
                        "name": "Singing Stone",
                        "name_export": "singing stone",
                        "name_clean": "singing_stone",
                        "image": "singing_stone.png",
                        "set": "Core",
                        "type": "Artifact",
                        "subtype": "Artifact",
                        "rarity": "rare",
                        "max_in_deck": 2,
                        "cost": 1,
                        "gems": "b",
                        "attack": 0,
                        "health": 12,
                        "keywords": null,
                        "text": "Stacking\r\nAll your minions have +1/+1 while they are occupying enchantments.\r\n",
                        "text_flavor": "She held Singasteinn to her ear and wondered if Loki had once heard the same otherworldly melody.",
                        "created_at": null,
                        "updated_at": null
                    },
                    {
                        "id": 19,
                        "id_rhino": 19,
                        "ide_faction": 1,
                        "rarity_index": 2,
                        "name": "Lore Broker",
                        "name_export": "lore broker",
                        "name_clean": "lore_broker",
                        "image": "lore_broker.png",
                        "set": "Core",
                        "type": "Creature",
                        "subtype": "Elf",
                        "rarity": "rare",
                        "max_in_deck": 2,
                        "cost": 2,
                        "gems": "b",
                        "attack": 2,
                        "health": 3,
                        "keywords": "[\"Lurker\"]",
                        "text": "Lurker\r\nBreach: Empower with 'Your opponent plays with their hand revealed'.\r\n",
                        "text_flavor": "Information is the only currency that matters these days, and those long-lived fey have the market cornered.",
                        "created_at": null,
                        "updated_at": null
                    },
                    {
                        "id": 17,
                        "id_rhino": 17,
                        "ide_faction": 1,
                        "rarity_index": 9,
                        "name": "Ice Spike",
                        "name_export": "ice spike",
                        "name_clean": "ice_spike",
                        "image": "ice_spike.png",
                        "set": "Core",
                        "type": "Spell",
                        "subtype": "Water Spell",
                        "rarity": "common",
                        "max_in_deck": 4,
                        "cost": 2,
                        "gems": "b",
                        "attack": 0,
                        "health": 0,
                        "keywords": null,
                        "text": "Give a minion Stunned until your next turn and deal 2 damage to it.\r\n",
                        "text_flavor": "Water is everywhere, why WOULDN'T you weaponize it?",
                        "created_at": null,
                        "updated_at": null
                    }
                ],
                "boneyard": [
                    {
                        "id": 2,
                        "id_rhino": 2,
                        "ide_faction": 1,
                        "rarity_index": 0,
                        "name": "Fey Plagiarist",
                        "name_export": "fey plagiarist",
                        "name_clean": "fey_plagiarist",
                        "image": "fey_plagiarist.png",
                        "set": "Core",
                        "type": "Creature",
                        "subtype": "Elf Hacker",
                        "rarity": "rare",
                        "max_in_deck": 2,
                        "cost": 1,
                        "gems": "b",
                        "attack": 1,
                        "health": 2,
                        "keywords": null,
                        "text": "Breach: Copy one of your opponent's artifacts or enchantments and add it to your hand without gems in its casting cost.\r\n",
                        "text_flavor": "\"If your IP is grokkable then it's open source.\" -Svartálfar artificer",
                        "created_at": null,
                        "updated_at": null
                    },
                    {
                        "id": 22,
                        "id_rhino": 21,
                        "ide_faction": 1,
                        "rarity_index": 5,
                        "name": "Root Of The World",
                        "name_export": "root of the world",
                        "name_clean": "root_of_the_world",
                        "image": "root_of_the_world.png",
                        "set": "Core",
                        "type": "enchant",
                        "subtype": "Earth Enchantment",
                        "rarity": "uncommon",
                        "max_in_deck": 3,
                        "cost": 2,
                        "gems": "bb",
                        "attack": 0,
                        "health": 0,
                        "keywords": null,
                        "text": "Occupying minion has '1 mana: Place this minion on the bottom of its owner's deck and draw your next minion'.\n",
                        "text_flavor": "This wood stands as proof that Yggdrasil's roots still connect many worlds.",
                        "created_at": null,
                        "updated_at": null
                    },
                    {
                        "id": 14,
                        "id_rhino": 14,
                        "ide_faction": 1,
                        "rarity_index": 7,
                        "name": "Einherjar Thane",
                        "name_export": "einherjar thane",
                        "name_clean": "einherjar_thane",
                        "image": "einherjar_thane.png",
                        "set": "Core",
                        "type": "Creature",
                        "subtype": "Undead",
                        "rarity": "common",
                        "max_in_deck": 4,
                        "cost": 2,
                        "gems": "b",
                        "attack": 2,
                        "health": 3,
                        "keywords": null,
                        "text": "Fully heals whenever an enemy minion dies.\r\n",
                        "text_flavor": "Live for the rush of combat, and be reminded of your glorious death.",
                        "created_at": null,
                        "updated_at": null
                    }
                ],
                "lane": {
                    "1": {
                            "creature":
                                {
                                    "id": 4,
                                    "id_rhino": 4,
                                    "ide_faction": 1,
                                    "rarity_index": 2,
                                    "name": "Freki Scout",
                                    "name_export": "freki scout",
                                    "name_clean": "freki_scout",
                                    "image": "freki_scout.png",
                                    "set": "Core",
                                    "type": "Creature",
                                    "subtype": "Valkyrie",
                                    "rarity": "common",
                                    "max_in_deck": 4,
                                    "cost": 1,
                                    "gems": "b",
                                    "attack": 2,
                                    "health": 1,
                                    "keywords": "[\"Swift\"]",
                                    "text": "Swift\r\n",
                                    "text_flavor": "\"Only way forward is to get your wheels dirty, sister.\" -Ingrid Stormdottir",
                                    "created_at": null,
                                    "updated_at": null
                                },
                            "enchant":
                                {
                                    "id": 22,
                                    "id_rhino": 21,
                                    "ide_faction": 1,
                                    "rarity_index": 5,
                                    "name": "Root Of The World",
                                    "name_export": "root of the world",
                                    "name_clean": "root_of_the_world",
                                    "image": "root_of_the_world.png",
                                    "set": "Core",
                                    "type": "enchant",
                                    "subtype": "Earth Enchantment",
                                    "rarity": "uncommon",
                                    "max_in_deck": 3,
                                    "cost": 2,
                                    "gems": "bb",
                                    "attack": 0,
                                    "health": 0,
                                    "keywords": null,
                                    "text": "Occupying minion has '1 mana: Place this minion on the bottom of its owner's deck and draw your next minion'.\n",
                                    "text_flavor": "This wood stands as proof that Yggdrasil's roots still connect many worlds.",
                                    "created_at": null,
                                    "updated_at": null
                                }
                        },

                    "2":
                        {
                            "creature":
                                {
                                    "id": 4,
                                    "id_rhino": 4,
                                    "ide_faction": 1,
                                    "rarity_index": 2,
                                    "name": "Freki Scout",
                                    "name_export": "freki scout",
                                    "name_clean": "freki_scout",
                                    "image": "freki_scout.png",
                                    "set": "Core",
                                    "type": "Creature",
                                    "subtype": "Valkyrie",
                                    "rarity": "common",
                                    "max_in_deck": 4,
                                    "cost": 1,
                                    "gems": "b",
                                    "attack": 2,
                                    "health": 1,
                                    "keywords": "[\"Swift\"]",
                                    "text": "Swift\r\n",
                                    "text_flavor": "\"Only way forward is to get your wheels dirty, sister.\" -Ingrid Stormdottir",
                                    "created_at": null,
                                    "updated_at": null
                                },
                            "enchant":
                                {
                                    "id": 12,
                                    "id_rhino": 12,
                                    "ide_faction": 1,
                                    "rarity_index": 1,
                                    "name": "Demolition Speedway",
                                    "name_export": "demolition speedway",
                                    "name_clean": "demolition_speedway",
                                    "image": "demolition_speedway.png",
                                    "set": "Core",
                                    "type": "enchant",
                                    "subtype": "Valkyrie Enchantment",
                                    "rarity": "uncommon",
                                    "max_in_deck": 3,
                                    "cost": 2,
                                    "gems": "bb",
                                    "attack": 0,
                                    "health": 0,
                                    "keywords": null,
                                    "text": "Occupying minion has +2/+0 and Overrun.\r\n",
                                    "text_flavor": "That destructive feeling when the road opens up and demands even higher speeds.",
                                    "created_at": null,
                                    "updated_at": null
                                }
                        },
                    "3":
                        {			"creature":
                                {
                                    "id": 4,
                                    "id_rhino": 4,
                                    "ide_faction": 1,
                                    "rarity_index": 2,
                                    "name": "Freki Scout",
                                    "name_export": "freki scout",
                                    "name_clean": "freki_scout",
                                    "image": "freki_scout.png",
                                    "set": "Core",
                                    "type": "Creature",
                                    "subtype": "Valkyrie",
                                    "rarity": "common",
                                    "max_in_deck": 4,
                                    "cost": 1,
                                    "gems": "b",
                                    "attack": 2,
                                    "health": 1,
                                    "keywords": "[\"Swift\"]",
                                    "text": "Swift\r\n",
                                    "text_flavor": "\"Only way forward is to get your wheels dirty, sister.\" -Ingrid Stormdottir",
                                    "created_at": null,
                                    "updated_at": null
                                },
                            "enchant": null
                        },
                    "4":
                        {
                            "enchant":
                                {
                                    "id": 1,
                                    "id_rhino": 1,
                                    "ide_faction": 1,
                                    "rarity_index": 0,
                                    "name": "Cairnhenge",
                                    "name_export": "cairnhenge",
                                    "name_clean": "cairnhenge",
                                    "image": "cairnhenge.png",
                                    "set": "Core",
                                    "type": "enchant",
                                    "subtype": "Earth Enchantment",
                                    "rarity": "common",
                                    "max_in_deck": 4,
                                    "cost": 1,
                                    "gems": "b",
                                    "attack": 0,
                                    "health": 0,
                                    "keywords": null,
                                    "text": "Occupying minion has +1/+1.\r\n",
                                    "text_flavor": "Stay put and think for yourself - you could learn a thing or two from those \"dumb rocks\".",
                                    "created_at": null,
                                    "updated_at": null
                                }
                        },
                    "5":
                        {
                            "creature":
                                {
                                    "id": 5,
                                    "id_rhino": 5,
                                    "ide_faction": 1,
                                    "rarity_index": 3,
                                    "name": "Grease Monkey",
                                    "name_export": "grease monkey",
                                    "name_clean": "grease_monkey",
                                    "image": "grease_monkey.png",
                                    "set": "Core",
                                    "type": "Creature",
                                    "subtype": "Valkyrie",
                                    "rarity": "common",
                                    "max_in_deck": 4,
                                    "cost": 1,
                                    "gems": "b",
                                    "attack": 1,
                                    "health": 2,
                                    "keywords": "[\"Lurker\"]",
                                    "text": "Lurker\r\n￼: Restore 3 health to a minion.\r\n",
                                    "text_flavor": "Next time you break it, I'll fix you too.",
                                    "created_at": null,
                                    "updated_at": null
                                },
                            "enchant":
                                {
                                    "id": 3,
                                    "id_rhino": 3,
                                    "ide_faction": 1,
                                    "rarity_index": 1,
                                    "name": "Field Of Poppies",
                                    "name_export": "field of poppies",
                                    "name_clean": "field_of_poppies",
                                    "image": "field_of_poppies.png",
                                    "set": "Core",
                                    "type": "enchant",
                                    "subtype": "Flora Enchantment",
                                    "rarity": "common",
                                    "max_in_deck": 4,
                                    "cost": 1,
                                    "gems": "b",
                                    "attack": 0,
                                    "health": 0,
                                    "keywords": null,
                                    "text": "Minions in the opposing three lanes have Fragile 1.\n",
                                    "text_flavor": "Eating or smoking them isn't necessary; the pollen alone is enough to dull the senses.",
                                    "created_at": null,
                                    "updated_at": null
                                }
                        },
                    "6":
                        {
                            "enchant":
                                {
                                    "id": 75,
                                    "id_rhino": 80,
                                    "ide_faction": 6,
                                    "rarity_index": 22,
                                    "name": "Verdant Jungle",
                                    "name_export": "verdant jungle",
                                    "name_clean": "verdant_jungle",
                                    "image": "verdant_jungle.png",
                                    "set": "Core",
                                    "type": "enchant",
                                    "subtype": "Earth Enchantment",
                                    "rarity": "common",
                                    "max_in_deck": 4,
                                    "cost": 1,
                                    "gems": "y",
                                    "attack": 0,
                                    "health": 0,
                                    "keywords": null,
                                    "text": "While occupied, you have 1 additional maximum mana.\r\nWhen you create a minion in this lane, gain 1 temporary mana.\r\n",
                                    "text_flavor": "Such growth comes only as the side effect of some magical pollutant.",
                                    "created_at": null,
                                    "updated_at": null
                                }
                        },
                    "7":
                        {
                            "enchant":
                                {
                                    "id": 44,
                                    "id_rhino": 42,
                                    "ide_faction": 1,
                                    "rarity_index": 5,
                                    "name": "Junkyard Valhalla",
                                    "name_export": "junkyard valhalla",
                                    "name_clean": "junkyard_valhalla",
                                    "image": "junkyard_valhalla.png",
                                    "set": "Core",
                                    "type": "enchant",
                                    "subtype": "Valkyrie Enchantment",
                                    "rarity": "mythic",
                                    "max_in_deck": 1,
                                    "cost": 4,
                                    "gems": "bb",
                                    "attack": 0,
                                    "health": 0,
                                    "keywords": null,
                                    "text": "If unoccupied at the start of your turn and you do not control a Dredge, return the bottom minion of your boneyard to this lane. It is now a Dredge and gets Ephemeral.\r\n",
                                    "text_flavor": " ",
                                    "created_at": null,
                                    "updated_at": null
                                }
                        }
                }
            },
        "p2":
            {
                "life": 10,
                "path": null,
                "power": null,
                "mana": 10,
                "gems": "",
                "burn": false,
                "hand": [],
                "boneyard": [],
                "deck": [],
                "lane": {
                    "1" : {"creature": null, "enchant": null},
                    "2" : {"creature": null, "enchant": null},
                    "3" : {"creature": null, "enchant": null},
                    "4" : {"creature": null, "enchant": null},
                    "5" : {"creature": null, "enchant": null},
                    "6" : {"creature": null, "enchant": null},
                    "7" : {"creature": null, "enchant": null}
                }
            }
    }
;

const playerDefaults = {
    life: 10,
    path: {id: 2, name: 'Disk of Circadia', image: 'disk_of_circardia.png', icon: 'paths/disk.png'},
    power: {id: 2, name: 'Foresight', image: 'foresight.png', icon: 'powers/foresight.png'},
    mana: 0,
    gems: '',
    burn: false,
    hand: [],
    boneyard: [],
    deck: [],
    lane: {
        "1": {creature: null, enchant: null},
        "2": {creature: null, enchant: null},
        "3": {creature: null, enchant: null},
        "4": {creature: null, enchant: null},
        "5": {creature: null, enchant: null},
        "6": {creature: null, enchant: null},
        "7": {creature: null, enchant: null},
    },
}

const puzzleDefaults = {
    p1: _.cloneDeep(playerDefaults),
    p2: _.cloneDeep(playerDefaults),
}

json.p2 = _.cloneDeep(json.p1);
json.p2.name = "Puzzle Opponent";
puzzleDefaults.p2.name = "Puzzle Opponent";

export {playerDefaults};
//export default json;
export default puzzleDefaults;